apiVersion: apps/v1
kind: Deployment
metadata:
  name: proceduresapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proceduresapi
  template:
    metadata:
      labels:
        app: proceduresapi
    spec:
      containers:
      - name: proceduresapi
        image: dpankov91/proceduresapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: proceduresapi
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: proceduresapi
  ports:
  - port: 5000
    targetPort: 3001		
    nodePort: 31101